before_install: true

install: ant -f build-dist.xml unzip-tomcat

before_script: true

script: true

after_success: true

after_failure: true

after_script: true

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

language: java