/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.asset.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetEntryStats service. Represents a row in the &quot;AssetEntryStats&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portlet.asset.model.impl.AssetEntryStatsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portlet.asset.model.impl.AssetEntryStatsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntryStats
 * @see com.liferay.portlet.asset.model.impl.AssetEntryStatsImpl
 * @see com.liferay.portlet.asset.model.impl.AssetEntryStatsModelImpl
 * @generated
 */
public interface AssetEntryStatsModel extends AttachedModel,
	BaseModel<AssetEntryStats>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset entry stats model instance should use the {@link AssetEntryStats} interface instead.
	 */

	/**
	 * Returns the primary key of this asset entry stats.
	 *
	 * @return the primary key of this asset entry stats
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset entry stats.
	 *
	 * @param primaryKey the primary key of this asset entry stats
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry stats ID of this asset entry stats.
	 *
	 * @return the entry stats ID of this asset entry stats
	 */
	public long getEntryStatsId();

	/**
	 * Sets the entry stats ID of this asset entry stats.
	 *
	 * @param entryStatsId the entry stats ID of this asset entry stats
	 */
	public void setEntryStatsId(long entryStatsId);

	/**
	 * Returns the group ID of this asset entry stats.
	 *
	 * @return the group ID of this asset entry stats
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this asset entry stats.
	 *
	 * @param groupId the group ID of this asset entry stats
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this asset entry stats.
	 *
	 * @return the company ID of this asset entry stats
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this asset entry stats.
	 *
	 * @param companyId the company ID of this asset entry stats
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this asset entry stats.
	 *
	 * @return the user ID of this asset entry stats
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this asset entry stats.
	 *
	 * @param userId the user ID of this asset entry stats
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this asset entry stats.
	 *
	 * @return the user uuid of this asset entry stats
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this asset entry stats.
	 *
	 * @param userUuid the user uuid of this asset entry stats
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this asset entry stats.
	 *
	 * @return the user name of this asset entry stats
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this asset entry stats.
	 *
	 * @param userName the user name of this asset entry stats
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this asset entry stats.
	 *
	 * @return the create date of this asset entry stats
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this asset entry stats.
	 *
	 * @param createDate the create date of this asset entry stats
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this asset entry stats.
	 *
	 * @return the modified date of this asset entry stats
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this asset entry stats.
	 *
	 * @param modifiedDate the modified date of this asset entry stats
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this asset entry stats.
	 *
	 * @return the fully qualified class name of this asset entry stats
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this asset entry stats.
	 *
	 * @return the class name ID of this asset entry stats
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this asset entry stats.
	 *
	 * @param classNameId the class name ID of this asset entry stats
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this asset entry stats.
	 *
	 * @return the class p k of this asset entry stats
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this asset entry stats.
	 *
	 * @param classPK the class p k of this asset entry stats
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the day of this asset entry stats.
	 *
	 * @return the day of this asset entry stats
	 */
	public int getDay();

	/**
	 * Sets the day of this asset entry stats.
	 *
	 * @param day the day of this asset entry stats
	 */
	public void setDay(int day);

	/**
	 * Returns the month of this asset entry stats.
	 *
	 * @return the month of this asset entry stats
	 */
	public int getMonth();

	/**
	 * Sets the month of this asset entry stats.
	 *
	 * @param month the month of this asset entry stats
	 */
	public void setMonth(int month);

	/**
	 * Returns the year of this asset entry stats.
	 *
	 * @return the year of this asset entry stats
	 */
	public int getYear();

	/**
	 * Sets the year of this asset entry stats.
	 *
	 * @param year the year of this asset entry stats
	 */
	public void setYear(int year);

	/**
	 * Returns the view count of this asset entry stats.
	 *
	 * @return the view count of this asset entry stats
	 */
	public int getViewCount();

	/**
	 * Sets the view count of this asset entry stats.
	 *
	 * @param viewCount the view count of this asset entry stats
	 */
	public void setViewCount(int viewCount);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetEntryStats assetEntryStats);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetEntryStats> toCacheModel();

	@Override
	public AssetEntryStats toEscapedModel();

	@Override
	public AssetEntryStats toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}